"""add inverter table

Revision ID: 1c69f6f8b10e
Revises: 4620b6f4a26e
Create Date: 2026-06-24 10:01:32.611916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c69f6f8b10e'
down_revision: Union[str, Sequence[str], None] = '4620b6f4a26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inverters')
    op.drop_column('projects', 'electrical_design')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('electrical_design', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('inverters',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rated_power', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_dc_power', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_branches', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_power_per_branch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_power_per_branch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_dc_voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mppt_voltage_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mppt_voltage_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_dc_current_per_branch', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('inverters_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inverters_pkey'))
    )
    # ### end Alembic commands ###
