"""create panels table and relations

Revision ID: 38345d2702a2
Revises: a9b1a5855f7c
Create Date: 2025-11-16 14:59:49.704569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38345d2702a2'
down_revision: Union[str, Sequence[str], None] = 'a9b1a5855f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooftops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('additional_panels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('initial_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transformed_additional_panels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('angle', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=False),
    sa.Column('panel_width', sa.Float(), nullable=False),
    sa.Column('panel_height', sa.Float(), nullable=False),
    sa.Column('spacing', sa.Float(), nullable=False),
    sa.Column('solar_production', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooftops')
    op.drop_table('projects')
    op.drop_table('panels')
    op.drop_table('users')
    # ### end Alembic commands ###
