"""add rooftop-panel relation

Revision ID: 4620b6f4a26e
Revises: 48e4162c01fb
Create Date: 2025-11-16 15:21:12.272177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4620b6f4a26e'
down_revision: Union[str, Sequence[str], None] = '48e4162c01fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooftops', sa.Column('panel_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'rooftops', 'panels', ['panel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooftops', type_='foreignkey')
    op.drop_column('rooftops', 'panel_id')
    # ### end Alembic commands ###
