"""add power column

Revision ID: 48e4162c01fb
Revises: eb49aceb8e9e
Create Date: 2025-11-16 15:14:19.264807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e4162c01fb'
down_revision: Union[str, Sequence[str], None] = 'eb49aceb8e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('power', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'power')
    # ### end Alembic commands ###
