"""add panel columns

Revision ID: 4c61973180f0
Revises: 38345d2702a2
Create Date: 2025-11-16 15:07:40.155532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c61973180f0'
down_revision: Union[str, Sequence[str], None] = '38345d2702a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('width', sa.Float(), nullable=False))
    op.add_column('panels', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('panels', sa.Column('spacing', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'spacing')
    op.drop_column('panels', 'height')
    op.drop_column('panels', 'width')
    # ### end Alembic commands ###
