"""Add vmp column to panels

Revision ID: a0f77bbb001d
Revises: f55e7e890338
Create Date: 2026-06-24 13:33:40.110695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f77bbb001d'
down_revision: Union[str, Sequence[str], None] = 'f55e7e890338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('vmp', sa.Float(), nullable=False))
    op.add_column('panels', sa.Column('voc', sa.Float(), nullable=False))
    op.add_column('panels', sa.Column('imp', sa.Float(), nullable=False))
    op.add_column('panels', sa.Column('isc', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panels', 'isc')
    op.drop_column('panels', 'imp')
    op.drop_column('panels', 'voc')
    op.drop_column('panels', 'vmp')
    # ### end Alembic commands ###
