"""update inverter nullable fields

Revision ID: f55e7e890338
Revises: 1c69f6f8b10e
Create Date: 2026-06-24 10:15:48.360422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55e7e890338'
down_revision: Union[str, Sequence[str], None] = '1c69f6f8b10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverters', 'mppt_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inverters', 'mppt_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
